NIGLOBAL = 160
NJGLOBAL = 800
GRID_CONFIG = "mercator"
ISOTROPIC = true
SOUTHLAT = -70.275597151116
LENLAT = 140.5511943022
LENLON = 40
TOPO_CONFIG = "file"
INPUTDIR = "/g/data/x77/amh157/mom6/input/anu-tub"
TOPO_FILE = "topog.nc"
TOPO_VARNAME = "topog"
MAXIMUM_DEPTH = 4000.0
NK = 75
ALE_COORDINATE_CONFIG = "FILE:st_edges_sigma.nc,interfaces=st_edges_sigma"
REGRIDDING_COORDINATE_UNITS = "Nondim"
MIN_THICKNESS = 1e-03
MAXIMUM_INT_DEPTH_CONFIG = "FNC1:5,8000.0,1.0,.01"
MAX_LAYER_THICKNESS_CONFIG = "FNC1:400,31000.0,0.1,.01"
BOUNDARY_EXTRAPOLATION = true
