NIGLOBAL = 160
NJGLOBAL = 800
GRID_CONFIG = "mercator"
ISOTROPIC = true
SOUTHLAT = -70.275597151116
LENLAT = 140.5511943022
LENLON = 40
TOPO_CONFIG = "file"
INPUTDIR = "/g/data/x77/amh157/mom6/input/anu-tub"
TOPO_FILE = "topog.nc"
TOPO_VARNAME = "topog"
MAXIMUM_DEPTH = 4000.0
NK = 75
ALE_COORDINATE_CONFIG = "FNC1:2,4000,4.5,.01"
ADAPT_TIMESCALE = 3600.0
ADAPT_BIHARMONIC_SMOOTHING = 1.0
ADAPT_ADJUSTMENT_SCALE = 0.1
REGRID_TIME_SCALE = 86400.0
REGRID_FILTER_SHALLOW_DEPTH = 50.0
REGRID_FILTER_DEEP_DEPTH = 300.0

